/// Flutter icons FreeCutIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FreeCutIcon
///      fonts:
///       - asset: fonts/FreeCutIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FreeCutIcon {
  FreeCutIcon._();

  static const _kFontFam = 'FreeCutIcon';
  static const String? _kFontPkg = null;

  static const IconData free_cut_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
